const VALID_DIFFICULTIES = new Set(["S-Rank", "A-Rank", "B-Rank", "C-Rank", "D-Rank", "E-Rank"]);
const VALID_LABELS = new Set(["bounty", "study", "daily", "guild"]);

function parseJsonCandidate(candidate) {
  try {
    return JSON.parse(candidate);
  } catch {
    return null;
  }
}

function extractJsonCandidates(content = "") {
  const candidates = [];
  const fencedJsonPattern = /```json\s*([\s\S]*?)```/gi;
  let match = fencedJsonPattern.exec(content);

  while (match) {
    candidates.push(match[1].trim());
    match = fencedJsonPattern.exec(content);
  }

  const firstObject = content.indexOf("{");
  const lastObject = content.lastIndexOf("}");
  if (firstObject >= 0 && lastObject > firstObject) {
    candidates.push(content.slice(firstObject, lastObject + 1));
  }

  const firstArray = content.indexOf("[");
  const lastArray = content.lastIndexOf("]");
  if (firstArray >= 0 && lastArray > firstArray) {
    candidates.push(content.slice(firstArray, lastArray + 1));
  }

  return candidates;
}

function unwrapQuestList(parsed) {
  if (Array.isArray(parsed)) return parsed;
  if (Array.isArray(parsed?.questifyQuests)) return parsed.questifyQuests;
  if (Array.isArray(parsed?.quests)) return parsed.quests;
  if (Array.isArray(parsed?.tasks)) return parsed.tasks;
  return [];
}

function normalizeChecklist(value) {
  if (!Array.isArray(value)) return [];

  return value
    .map((item) => (typeof item === "string" ? item : item?.text ?? item?.title ?? ""))
    .map((item) => item.trim())
    .filter(Boolean)
    .slice(0, 6);
}

function normalizeDeadline(value) {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";

  const pad = (part) => String(part).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

function normalizeQuestDraft(rawQuest, index) {
  const title = String(rawQuest?.title ?? rawQuest?.name ?? "").trim();
  if (!title) return null;

  const difficulty = String(rawQuest?.difficulty ?? rawQuest?.rank ?? "C-Rank").trim();
  const label = String(rawQuest?.label ?? rawQuest?.category ?? "study").trim().toLowerCase();

  return {
    checklist: normalizeChecklist(rawQuest?.checklist ?? rawQuest?.tasks ?? rawQuest?.subtasks),
    deadline: normalizeDeadline(rawQuest?.deadline ?? rawQuest?.dueAt ?? rawQuest?.due_at),
    description: String(rawQuest?.description ?? rawQuest?.details ?? "Generated by Guild Orb AI.").trim().slice(0, 520),
    difficulty: VALID_DIFFICULTIES.has(difficulty) ? difficulty : "C-Rank",
    id: `generated-${index}-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 36)}`,
    label: VALID_LABELS.has(label) ? label : "study",
    title: title.slice(0, 96),
  };
}

export function parseGeneratedQuestDrafts(content = "") {
  for (const candidate of extractJsonCandidates(content)) {
    const parsed = parseJsonCandidate(candidate);
    const questList = unwrapQuestList(parsed);
    const drafts = questList
      .map((quest, index) => normalizeQuestDraft(quest, index))
      .filter(Boolean)
      .slice(0, 8);

    if (drafts.length) return drafts;
  }

  return [];
}
